export const GET_HACKER_NEWS_ARTICLES_REQUEST = 'GET_HACKER_NEWS_ARTICLES_REQUEST'
export const GET_HACKER_NEWS_ARTICLES_SUCCESS = 'GET_HACKER_NEWS_ARTICLES_SUCCESS'
export const GET_HACKER_NEWS_ARTICLES_ERROR = 'GET_HACKER_NEWS_ARTICLES_ERROR'

export const SAVE_TO_FAVORITES = 'SAVE_TO_FAVORITES'
export const REMOVE_FROM_FAVORITES = 'REMOVE_FROM_FAVORITES'
